<?php
/**
 * Shadow Shinobi legacy player-output cleanup.
 *
 * The original files contain a mixture of Portuguese UTF-8 and mojibake that
 * survived an older encoding conversion. This compatibility map operates only
 * on rendered player output; gameplay identifiers are untouched.
 */
function legacy_player_cleanup($text) {
    static $map = array(
        // Common mojibake tokens.
        'Voc�' => 'You',
        'voc�' => 'you',
        'n�o' => 'not',
        'N�o' => 'Not',
        'j�' => 'already',
        'J�' => 'Already',
        'est�' => 'is',
        'Est�' => 'Is',
        'Gradua��o' => 'Standing',
        'gradua��o' => 'standing',
        'Conclu�do' => 'Complete',
        'conclu�do' => 'complete',
        'Conclu�da' => 'Complete',
        'conclu�da' => 'complete',
        'Indispon�vel' => 'Unavailable',
        'indispon�vel' => 'unavailable',
        'N�o Dispon�vel' => 'Not Available',
        'n�o dispon�vel' => 'not available',
        'Ol�' => 'Hello',
        'ol�' => 'hello',
        'B�nus' => 'Bonus',
        'b�nus' => 'bonus',
        'For�a' => 'Strength',
        'for�a' => 'strength',
        'Pr�ximo' => 'Next',
        'pr�ximo' => 'next',
        'Pr�xima' => 'Next',
        'pr�xima' => 'next',
        'Hist�rico' => 'History',
        'hist�rico' => 'history',
        'mensagens' => 'messages',
        'Mensagem' => 'Message',
        'mensagem' => 'message',
        'Pontos de Distribui��o' => 'Attribute Points',
        'Pontos de Natureza' => 'Nature Points',
        'Pontos de Vida' => 'Health',
        'Pontos de Chakra' => 'Essence',
        'Esperan�a' => 'Hope',
        'esperan�a' => 'hope',
        'Vit�ria' => 'Victory',
        'vit�ria' => 'victory',
        'Nenhum Item' => 'No Gear',
        'nenhum item' => 'no gear',
        'Estudante da Academia' => 'Academy Student',
        'Graduar-se' => 'Advance',
        'graduar-se' => 'advance',
        'Gradua��o Inicial' => 'Starting Standing',
        'Gradua��o 1' => 'Standing 1',
        'Gradua��o 2' => 'Standing 2',
        'Gradua��o 3' => 'Standing 3',
        'Gradua��o:' => 'Standing:',
        'gradua��o:' => 'standing:',

        // Common legacy UI fragments that survive mixed-language rendering.
        'O jogador ' => 'Operative ',
        'o jogador ' => 'operative ',
        'O operative ' => 'Operative ',
        'o operative ' => 'operative ',
        ' est? te chamando para realizar uma troca.' => ' is inviting you to trade.',
        ' est� te chamando para realizar uma troca.' => ' is inviting you to trade.',
        ' est� te chamando para realizar uma troca' => ' is inviting you to trade',
        'est? te chamando para realizar uma troca' => 'is inviting you to trade',
        'est� te chamando para realizar uma troca' => 'is inviting you to trade',
        'Voc&ecirc; est&aacute; exploring o world map, nada aconteceu. Continue explorando usando os bot&otilde;es de dire&ccedil;&atilde;o ou o menu Viajar.' => 'You are exploring the world map; nothing happened. Continue exploring with the movement controls or the Travel menu.',
        'Voc&ecirc; est&aacute; exploring o world map.' => 'You are exploring the world map.',
        'Você está exploring o world map.' => 'You are exploring the world map.',
        'O jogador ' => 'Operative ',
        'Realizar uma Troca' => 'Open Trade',
        'Realizar um Duelo' => 'Start Challenge',
        'Abrir Chat Global' => 'Open Open Channel',
        'Abrir o F&oacute;rum In-Game' => 'Open In-Game Forum',
        'Abrir o Fórum In-Game' => 'Open In-Game Forum',
        'Abrir Chat' => 'Open Chat',
        'Nenhum Item' => 'No Gear',
        'Escolha o Item(Mochila)' => 'Choose Gear (Pack)',
        'Nome do Jogador' => 'Operative Name',
        'Ryou para Trocar' => 'Coin to Trade',
        'Meu Ryou' => 'My Coin',
        'Realizar Nova Troca' => 'Open New Trade',
        'Aceitar Troca' => 'Accept Trade',
        'Aguardando o outro jogador' => 'Waiting for the other operative',
        'aguardando o outro jogador' => 'waiting for the other operative',
        'pressione o bot?o Realizar Nova Troca' => 'press Open New Trade',
        'pressione o botão Realizar Nova Troca' => 'press Open New Trade',
        'Viajar' => 'Travel',
        'botões de direção' => 'movement controls',
        'bot?es de dire??o' => 'movement controls',
        'botões de direcção' => 'movement controls',
        'direção' => 'direction',
        'direc??o' => 'direction',
        'direc??' => 'direction',
        'nada aconteceu' => 'nothing happened',
        'Continue explorando' => 'Continue exploring',
        'continuar explorando' => 'continue exploring',
        'usando' => 'using',
        'menu Viajar' => 'Travel menu',
        'Trade' => 'Trade',

        // Standing / graduation presentation.
        'a pr�xima gradua��o dispon�vel para voc� � a gradua��o de' => 'the next available Standing for you is',
        'caso voc� possua os requirements, voc� pode se graduar abaixo agora mesmo.' => 'once you meet the requirements, you can advance below now.',
        'As gradua��es te dar�o b�nus para que voc� se torne um shinobi ainda mais completo.' => 'Standing advancements grant bonuses that make your operative more capable.',
        'Ser um Estudante da Academia' => 'Be an Academy Student',
        'completar 7 miss%EF%BF%BDes operatives' => 'complete 7 contracts',
        'completar 10 miss%EF%BF%BDes operatives' => 'complete 10 contracts',
        'completar 20 miss%EF%BF%BDes operatives' => 'complete 20 contracts',
        'Ser um Initiate' => 'Hold Initiate Standing',
        'obter o gear' => 'obtain the gear',
        '30 de Destreza' => '30 Dexterity',
        '20 de Destreza' => '20 Dexterity',
        '5% de B%EF%BF%BDnus de Experi%EF%BF%BDncia' => '5% Insight Bonus',
        '5% de B%EF%BF%BDnus de Coin' => '5% Coin Bonus',

        // Existing full gameplay messages.
        'Voc� deve selecionar um Jutsu primeiro.' => 'Select an Art first.',
        'Voc� ainda n�o aprendeu esse Jutsu. Por favor volte e tente novamente.' => 'You have not learned that Art yet. Return and try again.',
        'Voc� n�o tem chakra suficiente para usar o(a) ' => 'You do not have enough Essence to use ',
        'Seu jutsu foi super efetivo.' => 'Your Art was highly effective.',
        'Seu jutsu foi pouco efetivo.' => 'Your Art was less effective.',
        'Voc� usou: ' => 'You used: ',
        'O inimigo � imune a seu Jutsu.' => 'The threat is immune to your Art.',
        'O inimigo est� dormindo.' => 'The threat is asleep.',
        'O inimigo continua dormindo.' => 'The threat remains asleep.',
        'O inimigo acordou.' => 'The threat woke up.',
        'Voc� fugiu de um ataque. Nenhum dano foi recebido.' => 'You avoided an attack. No damage was taken.',
        'O inimigo provocou no total, ' => 'The threat dealt a total of ',
        'Voc� atacou o inimigo provocando ' => 'You attacked the threat for ',
        'Voc� morreu.' => 'You were defeated.',
        'Parab�ns.' => 'Congratulations.',
        'Voc� derrotou o inimigo ' => 'You defeated the threat ',
        'Voc� passou de n�vel!' => 'Your Standing increased!',
        'Voc� ganhou:' => 'You gained:',
        'Pontos de Viagem' => 'Travel Points',
        'de ataque.' => ' Attack.',
        'de defesa.' => ' Defense.',
        'Voc� n�o pode fazer nenhum movimento enquanto estiver em um duelo.' => 'You cannot move while in a Challenge.',
        'Clique ' => 'Click ',
        'aqui' => 'here',
        'para resetar seu Duelo atual.' => 'to reset your current Challenge.',
        'Sua mochila j� est� cheia.' => 'Your Pack is already full.',
        'O item foi equipado ou adicionado � mochila com sucesso.' => 'The gear was equipped or added to your Pack successfully.',
        'Voce so pode acessar essa funcao dentro de uma cidade!' => 'This function can only be accessed inside a Settlement.',
        'Voce nao pode retirar mais que 99999 Ryou.' => 'You cannot withdraw more than 99999 Coin.',
        'Voce nao pode retirar mais que seu dinheiro no banco.' => 'You cannot withdraw more than your Vault balance.',
        'Voce depositou ' => 'You deposited ',
        ' e retirou ' => ' and withdrew ',
        ' do Banco.' => ' from the Vault.',
        'Nao existe nenhum jogador com esse Nome.' => 'No operative with that name exists.',
        'Voce nao pode doar Ryou para si mesmo.' => 'You cannot transfer Coin to yourself.',
        'A quantidade de Ryou deve ser um numero.' => 'The Coin amount must be a number.',
        'Voce nao pode doar menos que 1 Ryou.' => 'You cannot transfer less than 1 Coin.',
        'Ryou enviado com sucesso.' => 'Coin transferred successfully.',
        'Voce nao pode doar Itens, voce nao tem nenhum no Banco.' => 'You cannot transfer gear because your Vault is empty.',
        'Voce nao possui espacos livres na sua Mochila. Libere algum espaco.' => 'You have no free Pack space. Free a slot first.',
        'Voce nao possui Slots Livres para Equipar e tambem nao possui espaco livre em sua Mochila. Libere algum espaco.' => 'You have no free Gear slot and no free Pack space. Free a slot first.'
    );

    return strtr($text, $map);
}
?>
