<?php
$template = <<<THEVERYENDOFYOU
<style>
.ss-public-profile{width:min(100%,680px);padding:14px;background:#0a0d12;color:#edf2f7;font-family:Inter,system-ui,-apple-system,"Segoe UI",Tahoma,sans-serif}.ss-public-profile *{box-sizing:border-box}.ss-public-head{display:flex;align-items:center;gap:12px;padding:13px;border:1px solid #303947;border-radius:9px;background:linear-gradient(135deg,#1b222c,#0f141b)}.ss-public-avatar{width:72px;height:72px;object-fit:cover;border-radius:9px;border:1px solid #4e5968}.ss-public-head h1{margin:0 0 3px;font-size:1.25rem}.ss-public-head p{margin:0;color:#98a4b2}.ss-public-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:9px}.ss-public-card{padding:12px;border:1px solid #303947;border-radius:8px;background:#11161d}.ss-public-card h2{margin:0 0 8px;color:#98a4b2;font-size:.72rem;text-transform:uppercase;letter-spacing:.14em}.ss-public-stats{display:grid;gap:4px}.ss-public-stat{display:flex;justify-content:space-between;gap:10px;padding:5px 6px;border-radius:5px;background:rgba(255,255,255,.025)}.ss-public-stat span{color:#98a4b2}.ss-public-stat b{text-align:right}.ss-public-equip{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.ss-public-equip div{display:grid;place-items:center;min-height:46px;padding:4px;background:#0b0f15;border:1px solid #303947;border-radius:6px}.ss-public-equip img{max-width:34px;max-height:34px}.ss-public-techniques{line-height:1.5;color:#cfd6de}.ss-public-techniques br{display:block;margin-bottom:2px}.ss-public-role{color:#d7dce3;font-size:.68rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}
@media(max-width:600px){.ss-public-grid{grid-template-columns:1fr}.ss-public-head{align-items:flex-start}}
</style>
<section class="ss-public-profile" aria-label="Player profile">
  <header class="ss-public-head"><img class="ss-public-avatar" src="layoutnovo/avatares/{{avatar}}.jpg" alt="{{charname}} avatar"><div><span class="ss-public-role">PLAYER PROFILE</span><h1>{{charname}}</h1>{{adm}}<p>{{charclass}} · Grade {{graduacao}}</p></div></header>
  <div class="ss-public-grid">
    <section class="ss-public-card"><h2>Progression</h2><div class="ss-public-stats"><div class="ss-public-stat"><span>Level</span><b>{{level}}</b></div><div class="ss-public-stat"><span>Experience</span><b>{{experience}} {{plusexp}}</b></div><div class="ss-public-stat"><span>Next level</span><b>{{nextlevel}}</b></div><div class="ss-public-stat"><span>Gold</span><b>{{gold}} {{plusgold}}</b></div><div class="ss-public-stat"><span>Drop rate</span><b>+{{droprate}}%</b></div></div></section>
    <section class="ss-public-card"><h2>Resources</h2><div class="ss-public-stats"><div class="ss-public-stat"><span>HP</span><b>{{currenthp}} / {{maxhp}}</b></div><div class="ss-public-stat"><span>Essence</span><b>{{currentmp}} / {{maxmp}}</b></div><div class="ss-public-stat"><span>Travel</span><b>{{currenttp}} / {{maxtp}}</b></div><div class="ss-public-stat"><span>Natural</span><b>{{currentnp}} / {{maxnp}}</b></div><div class="ss-public-stat"><span>Elemental</span><b>{{currentep}} / {{maxep}}</b></div></div></section>
    <section class="ss-public-card"><h2>Attributes</h2><div class="ss-public-stats"><div class="ss-public-stat"><span>Strength</span><b>{{strength}}</b></div><div class="ss-public-stat"><span>Dexterity</span><b>{{dexterity}}</b></div><div class="ss-public-stat"><span>Attack</span><b>{{attackpower}}</b></div><div class="ss-public-stat"><span>Defense</span><b>{{defensepower}}</b></div><div class="ss-public-stat"><span>Agility</span><b>{{agilidade}}</b></div><div class="ss-public-stat"><span>Luck</span><b>{{sorte}}</b></div><div class="ss-public-stat"><span>Determination</span><b>{{determinacao}}</b></div><div class="ss-public-stat"><span>Precision</span><b>{{precisao}}</b></div><div class="ss-public-stat"><span>Intelligence</span><b>{{inteligencia}}</b></div></div></section>
    <section class="ss-public-card"><h2>Loadout</h2><div class="ss-public-equip"><div><img src="layoutnovo/equipamentos/{{weaponid}}.gif" alt="{{weaponname}}"></div><div><img src="layoutnovo/equipamentos/{{armorid}}.gif" alt="{{armorname}}"></div><div><img src="layoutnovo/equipamentos/{{shieldid}}.gif" alt="{{shieldname}}"></div><div><img src="layoutnovo/equipamentos/drops/{{slot1id}}.gif" alt="{{slot1name}}"></div><div><img src="layoutnovo/equipamentos/drops/{{slot2id}}.gif" alt="{{slot2name}}"></div><div><img src="layoutnovo/equipamentos/drops/{{slot3id}}.gif" alt="{{slot3name}}"></div></div></section>
  </div>
  <section class="ss-public-card" style="margin-top:9px"><h2>Techniques</h2><div class="ss-public-techniques">{{magiclist}}</div></section>
</section>
THEVERYENDOFYOU;
?>