<?php
global $userrow;
if ($userrow["authlevel"] == 1) {$userrow["adm"] = "<span class=\"ss-role ss-role--admin\">Administrator</span>";}
elseif ($userrow["acesso"] == 2){$userrow["adm"] = "<span class=\"ss-role ss-role--tutor\">Tutor</span>";}
elseif ($userrow["acesso"] == 3){$userrow["adm"] = "<span class=\"ss-role ss-role--gm\">GameMaster</span>";}
else {$userrow["adm"] = "";}

$durabm = explode(",",$userrow["durabilidade"]);
for ($i = 1; $i < 7; $i ++) {
    if (isset($durabm[$i]) && $durabm[$i] == "X") {$durabm[$i] = "*";}
}
if ($userrow["senjutsuhtml"] != "") {$userrow["magiclist"] = "<span class=\"ss-ability-tag\">Senjutsu</span><br>".$userrow["magiclist"];}
if ($userrow["jutsudebuscahtml"] != "") {$userrow["magiclist"] = "<span class=\"ss-ability-tag\">Search Technique</span><br>".$userrow["magiclist"];}

$template = <<<THEVERYENDOFYOU
<style>
.ss-char-sheet{width:min(100%,720px);margin:0 auto;padding:14px;background:#0a0d12;color:#edf2f7;font-family:Inter,system-ui,-apple-system,"Segoe UI",Tahoma,sans-serif;font-size:13px;line-height:1.45}.ss-char-sheet *{box-sizing:border-box}.ss-char-head{display:flex;gap:14px;align-items:center;padding:14px;border:1px solid #303947;border-radius:10px;background:linear-gradient(135deg,#1b222c,#0f141b)}.ss-char-avatar{width:90px;height:90px;object-fit:cover;border:1px solid #4e5968;border-radius:10px}.ss-char-head h1{margin:2px 0 4px;font-size:1.35rem}.ss-char-head p{margin:2px 0;color:#98a4b2}.ss-char-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.ss-char-panel{padding:13px;border:1px solid #303947;border-radius:9px;background:#11161d}.ss-char-panel h2{margin:0 0 9px;padding-bottom:7px;border-bottom:1px solid #252d38;font-size:.78rem;text-transform:uppercase;letter-spacing:.14em;color:#98a4b2}.ss-stat-list{display:grid;gap:5px}.ss-stat{display:flex;justify-content:space-between;gap:12px;padding:6px 7px;border-radius:5px;background:rgba(255,255,255,.025)}.ss-stat span{color:#98a4b2}.ss-stat b{color:#edf2f7;text-align:right}.ss-equipment-preview{display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:52px 52px;gap:6px;padding:9px;border-radius:8px;background:radial-gradient(circle,#232c37,#0b0f15 76%)}.ss-eq{display:grid;place-items:center}.ss-eq img{max-width:38px;max-height:38px}.ss-eq--shield{grid-column:2}.ss-eq--weapon{grid-column:1;grid-row:2}.ss-eq--armor{grid-column:2;grid-row:2}.ss-eq--secondary{grid-column:3;grid-row:2}.ss-slots-preview{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:7px}.ss-slots-preview img{width:34px;height:34px;object-fit:contain;margin:auto}.ss-equipment-rows{display:grid;gap:4px;margin-top:10px}.ss-equipment-rows>div{display:grid;grid-template-columns:20px 1fr auto;gap:7px;align-items:center;padding:6px 7px;border:1px solid rgba(255,255,255,.05);border-radius:5px}.ss-equipment-rows img{width:18px;height:18px}.ss-equipment-rows span{color:#98a4b2;font-size:.68rem}.ss-equipment-rows b{font-size:.74rem}.ss-equipment-rows small{color:#687585;font-size:.63rem}.ss-ability-tag{color:#9ad7b0;font-weight:700}.ss-role{display:inline-block;margin-bottom:5px;font-size:.68rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#d7dce3}.ss-share{margin-top:10px;padding:9px;border:1px dashed #303947;border-radius:7px;background:#0c1016}.ss-share input{width:100%;padding:7px;background:#080b10;color:#98a4b2;border:1px solid #303947;border-radius:5px}
@media(max-width:600px){.ss-char-grid{grid-template-columns:1fr}.ss-char-head{align-items:flex-start}.ss-char-avatar{width:72px;height:72px}}
</style>
<section class="ss-char-sheet" aria-label="Character sheet">
  <header class="ss-char-head">
    <img class="ss-char-avatar" src="layoutnovo/avatares/{{avatar}}.jpg" alt="{{charname}} avatar">
    <div><span style="color:#98a4b2;font-size:.68rem;letter-spacing:.16em;text-transform:uppercase">CHARACTER SHEET</span><h1>{{charname}}</h1>$userrow[adm]<p>{{charclass}} · {{difficulty}} · Grade {{graduacao}}</p></div>
  </header>
  <div class="ss-char-grid">
    <section class="ss-char-panel"><h2>Progression</h2><div class="ss-stat-list"><div class="ss-stat"><span>Level</span><b>{{level}}</b></div><div class="ss-stat"><span>Experience</span><b>{{experience}} {{plusexp}}</b></div><div class="ss-stat"><span>Next level</span><b>{{nextlevel}}</b></div><div class="ss-stat"><span>Ryou</span><b>{{gold}} {{plusgold}}</b></div><div class="ss-stat"><span>Drop rate</span><b>+{{droprate}}%</b></div></div></section>
    <section class="ss-char-panel"><h2>Resources</h2><div class="ss-stat-list"><div class="ss-stat"><span>HP</span><b>{{currenthp}} / {{maxhp}}</b></div><div class="ss-stat"><span>Chakra</span><b>{{currentmp}} / {{maxmp}}</b></div><div class="ss-stat"><span>Travel</span><b>{{currenttp}} / {{maxtp}}</b></div><div class="ss-stat"><span>Natural</span><b>{{currentnp}} / {{maxnp}}</b></div><div class="ss-stat"><span>Elemental</span><b>{{currentep}} / {{maxep}}</b></div></div></section>
    <section class="ss-char-panel"><h2>Core attributes</h2><div class="ss-stat-list"><div class="ss-stat"><span>Strength</span><b>{{strength}}</b></div><div class="ss-stat"><span>Dexterity</span><b>{{dexterity}}</b></div><div class="ss-stat"><span>Attack power</span><b>{{attackpower}}</b></div><div class="ss-stat"><span>Defense power</span><b>{{defensepower}}</b></div></div></section>
    <section class="ss-char-panel"><h2>Advanced attributes</h2><div class="ss-stat-list"><div class="ss-stat"><span>Agility</span><b>{{agilidade}}</b></div><div class="ss-stat"><span>Luck</span><b>{{sorte}}</b></div><div class="ss-stat"><span>Determination</span><b>{{determinacao}}</b></div><div class="ss-stat"><span>Precision</span><b>{{precisao}}</b></div><div class="ss-stat"><span>Intelligence</span><b>{{inteligencia}}</b></div></div></section>
    <section class="ss-char-panel"><h2>Loadout</h2><div class="ss-equipment-preview"><div class="ss-eq ss-eq--shield"><img src="layoutnovo/equipamentos/{{shieldid}}.png" alt="{{shieldname}}"></div><div class="ss-eq ss-eq--weapon"><img src="layoutnovo/equipamentos/{{weaponid}}.png" alt="{{weaponname}}"></div><div class="ss-eq ss-eq--armor"><img src="layoutnovo/equipamentos/{{armorid}}.png" alt="{{armorname}}"></div><div class="ss-eq ss-eq--secondary"><img src="layoutnovo/equipamentos/{{weaponid}}d.png" alt="Secondary weapon"></div></div><div class="ss-slots-preview"><img src="layoutnovo/equipamentos/drops/{{slot1id}}.png" alt="{{slot1name}}"><img src="layoutnovo/equipamentos/drops/{{slot2id}}.png" alt="{{slot2name}}"><img src="layoutnovo/equipamentos/drops/{{slot3id}}.png" alt="{{slot3name}}"></div></section>
    <section class="ss-char-panel"><h2>Equipped items</h2><div class="ss-equipment-rows"><div><img src="images/icon_weapon.gif" alt=""><span>Weapon</span><b>{{weaponname}}</b><small>$durabm[1]</small></div><div><img src="images/icon_armor.gif" alt=""><span>Armor</span><b>{{armorname}}</b><small>$durabm[2]</small></div><div><img src="images/icon_shield.gif" alt=""><span>Shield</span><b>{{shieldname}}</b><small>$durabm[3]</small></div><div><img src="images/orb.gif" alt=""><span>Slot 1</span><b>{{slot1name}}</b><small>$durabm[4]</small></div><div><img src="images/orb.gif" alt=""><span>Slot 2</span><b>{{slot2name}}</b><small>$durabm[5]</small></div><div><img src="images/orb.gif" alt=""><span>Slot 3</span><b>{{slot3name}}</b><small>$durabm[6]</small></div></div></section>
  </div>
  <section class="ss-char-panel" style="margin-top:10px"><h2>Techniques</h2><div>{{magiclist}}</div></section>
  <div class="ss-share"><span style="display:block;color:#98a4b2;font-size:.68rem;margin-bottom:5px">Character link</span><input type="text" readonly value="mostrarchar.php?nomechar={{charname}}" aria-label="Character link"></div>
</section>
THEVERYENDOFYOU;
?>